### ISSUE TITLE
command line 运行 fastlane fir_cli   api_token: xxxxxxxxxxxxxxxxx 报错

### ISSUE THREAD

**Issue by relaxfinger** [FIRHQ/fastlane-plugin-fir_cli#1]
[19:43:56]: ---------------------
[19:43:56]: --- Step: fir_cli ---
[19:43:56]: ---------------------
[19:43:56]: The fir_cli plugin is working!

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	21: from /usr/local/bin/fastlane:23:in `<main>'
	20: from /usr/local/bin/fastlane:23:in `load'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-fir_cli-2.0.0/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb:25:in `run'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.0.beta2/lib/fir/util/publish.rb:11:in `publish'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.0.beta2/lib/fir/util/publish.rb:191:in `initialize_publish_options': undefined method `_info' for Fastlane::Actions::FirHelper:Class (NoMethodError)
Did you mean?  info
	21: from /usr/local/bin/fastlane:23:in `<main>'
	20: from /usr/local/bin/fastlane:23:in `load'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-fir_cli-2.0.0/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb:25:in `run'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.0.beta2/lib/fir/util/publish.rb:11:in `publish'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.0.beta2/lib/fir/util/publish.rb:191:in `initialize_publish_options': [!] undefined method `_info' for Fastlane::Actions::FirHelper:Class (NoMethodError)
Did you mean?  info

**Comment by jicheng1014** [comment]
参数给的不对吧

**Comment by relaxfinger** [comment]
同样的参数 plugin 运行ok，命令行下运行报错
