### ISSUE TITLE
2.0.3.4提交成功后报错

### ISSUE THREAD

**Issue by GG526** [FIRHQ/fastlane-plugin-fir_cli#11]
Restclient error, body =
400 Bad Request
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | ios          |
| PLATFORM_NAME    | ios          |
| LANE_NAME        | ios FireTest |
+------------------+--------------+
[16:41:57]: 400 Bad Request

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | fir_cli          | 24          |
+------+------------------+-------------+

[16:41:57]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Distribute to hockeyapp suddenly failing
    https://github.com/fastlane/fastlane/issues/400 [closed] 8 💬
    22 Sep 2016

➡️  400 Bad request
    https://github.com/fastlane/fastlane/issues/15587 [closed] 3 💬
    2 weeks ago

➡️  400 Bad Request
    https://github.com/fastlane/fastlane/issues/12449 [closed] 1 💬
    04 Jul 2018

and 30 more at: https://github.com/fastlane/fastlane/search?q=400%20Bad%20Request&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	44: from /Users/seven/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	43: from /Users/seven/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	42: from /Users/seven/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	41: from /Users/seven/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	40: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	39: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	38: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	37: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	36: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	35: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	34: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	33: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	32: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	31: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	30: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	29: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	28: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	27: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	26: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	25: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	24: from Fastfile:167:in `block (2 levels) in parsing_binding'
	23: from Fastfile:174:in `fire'
	22: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	21: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	20: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	19: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	18: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	17: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	16: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	15: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-plugin-fir_cli-2.0.3.4/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb:31:in `run'
	14: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fir-cli-2.0.3.3/lib/fir/util/publish.rb:15:in `publish'
	13: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fir-cli-2.0.3.3/lib/fir/util/publish.rb:84:in `upload_app'
	12: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fir-cli-2.0.3.3/lib/fir/util/publish.rb:126:in `update_app_info'
	11: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:19:in `block (2 levels) in <module:DefaultRestModule>'
	10: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `basic_request'
	 9: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `times'
	 8: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:66:in `block in basic_request'
	 7: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	 6: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	 5: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	 4: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:910:in `start'
	 3: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
	 2: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
	 1: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 400 Bad Request (RestClient::BadRequest)

**Comment by jicheng1014** [comment]
抱歉  这个是因为我们的api 在接入cdn 后  cdn 不支持 patch method 导致的  

最新版本的插件已经改为使用 put  method
