### ISSUE TITLE
fastlane安装插件的时候报错

### ISSUE THREAD

**Issue by XmYhkj** [FIRHQ/fastlane-plugin-fir_cli#14]
`$ fastlane add_plugin fir_cli
[17:51:41]: fastlane detected a Gemfile in the current directory
[17:51:41]: however it seems like you don't use `bundle exec`
[17:51:41]: to launch fastlane faster, please use
[17:51:41]: 
[17:51:41]: $ bundle exec fastlane add_plugin fir_cli
[17:51:41]: 
[17:51:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:51:47]: Error loading plugin 'fastlane-plugin-fir_cli': cannot load such file -- fir
+------------------------+---------+------------------+
|                    Used plugins                     |
+------------------------+---------+------------------+
| Plugin                 | Version | Action           |
+------------------------+---------+------------------+
| fastlane-plugin-firim  | 0.2.0   | firim            |
| fastlane-plugin-pgyer  | 0.2.2   | pgyer            |
| fastlane-plugin-fir_c  | 2.0.8   | No actions found |
| li                     |         |                  |
+------------------------+---------+------------------+

[17:51:48]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/Jagtu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/unf_ext-0.0.7.5/ext/unf_ext
/Users/Jagtu/.fastlane/bin/bundle/bin/ruby -r
./siteconf20200323-32219-1dr6pho.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/Jagtu/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The
compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:541:in
`try_link0'
	from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
	from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:966:in `block in
have_library'
from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in
checking_for'
from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2
levels) in postpone'
	from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in
postpone'
	from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in
`checking_for'
from /Users/Jagtu/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:961:in
`have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/Users/Jagtu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/unf_ext-0.0.7.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/Jagtu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/unf_ext-0.0.7.5 for
inspection.
Results logged to
/Users/Jagtu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/unf_ext-0.0.7.5/gem_make.out

An error occurred while installing unf_ext (0.0.7.5), and Bundler
cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.5'` succeeds before bundling.
`

**Comment by jicheng1014** [comment]
老哥  ruby 版本需要>=2.4.0
