### ISSUE TITLE
dingTalk问题

### ISSUE THREAD

**Issue by Wanglw2015** [FIRHQ/fastlane-plugin-fir_cli#18]
使用过dingtalk_access_token后,即使移除,网页上的配置也不起作用了

**Comment by jicheng1014** [comment]
web 的配置跟这个没有关系   fir_cli 是客户端发送的   web 的是服务器发送的 

新版的 dingtalk 在webhook的 时候有验证  建议将自己app 的名字加到dingtalk 的关键字中

**Comment by Wanglw2015** [comment]
通过添加App名称, 解决问题了
