### ISSUE TITLE
请问怎么发钉钉通知呢？

### ISSUE THREAD

**Issue by relaxfinger** [FIRHQ/fastlane-plugin-fir_cli#2]
是在  fir_cli 中 增加 dingtalk_access_token: "token"  ?

**Comment by jicheng1014** [comment]
其实在  web界面中 可以给app 直接加上 dingtalk 的通知地址的

**Comment by jicheng1014** [comment]
实在不行的话我计划写个通用的  同步 fir-cli 的参数到 这个插件上吧

**Comment by jicheng1014** [comment]
已经更新到了  2.0.0.1 版本.....你可以更新下你的插件

**Comment by relaxfinger** [comment]
多谢！
