### ISSUE TITLE
上传文件的时候，长时间没有反馈，被CI直接中断

### ISSUE THREAD

**Issue by lyf571321556** [FIRHQ/fastlane-plugin-fir_cli#22]
INFO [2021-02-02 16:49:27.11]: The fir_cli plugin is working!
I, [2021-02-02T16:49:33.873747 #6155]  INFO -- : Fetching ai.ones.project.android.preview@fir.im uploading info......
I, [2021-02-02T16:49:33.873803 #6155]  INFO -- : Uploading app: xx-P-1.0(Build 1)
I, [2021-02-02T16:49:36.825114 #6155]  INFO -- : Publishing app via >.......
I, [2021-02-02T16:49:36.825170 #6155]  INFO -- : ✈ -------------------------------------------- ✈
I, [2021-02-02T16:49:36.825185 #6155]  INFO -- : begin to upload ...
D, [2021-02-02T16:49:36.825248 #6155] DEBUG -- : begin to upload icon
D, [2021-02-02T16:49:36.825310 #6155] DEBUG -- : icon_url = https://fir-app-icon.oss-cn-beijing.aliyuncs.com/9f54b6377ec862fedc0d55b0375cf6d74223d6f8, icon_info = #<File:0x00000001ea6450>
D, [2021-02-02T16:49:43.944420 #6155] DEBUG -- : upload icon finished
D, [2021-02-02T16:49:43.944513 #6155] DEBUG -- : begin to upload binary ...
D, [2021-02-02T16:49:43.944566 #6155] DEBUG -- : binary_url = https://fir-app-binary.oss-cn-beijing.aliyuncs.com/7b99c36d45e77caa283e8571c2fb8a2b2af450e3.apk, binary_info = #<File:0x00000004ff2298>
D, [2021-02-02T16:49:43.944580 #6155] DEBUG -- : {"CONTENT-DISPOSITION"=>"attachment; filename* = UTF-8''app-preview-release.apk", "Content-Type"=>"application/vnd.android.package-archive", "date"=>"Tue, 02 Feb 2021 16:49:36 GMT", "x-oss-date"=>"Tue, 02 Feb 2021 16:49:36 GMT", "authorization"=>"OSS LTAIH45wjMAbqQjW:uCTZDTWSNbPMj+wX1kRnyr9PfUg="}
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated

在travis平台构建，上传的时候出现这种问题。

**Comment by lyf571321556** [comment]
@jicheng1014

**Comment by jicheng1014** [comment]
travis ci 需要使用海外加速参数    目前这个版本不支持这个参数  但是  fir-cli 支持  你可以试试  

下次升级的时候我会将这个参数同步到 fastlane 插件中

**Comment by lyf571321556** [comment]
> travis ci 需要使用海外加速参数 目前这个版本不支持这个参数 但是 fir-cli 支持 你可以试试
> 
> 下次升级的时候我会将这个参数同步到 fastlane 插件中

期待下一个版本

**Comment by jicheng1014** [comment]
已支持根据上传 ip 自动开启海外加速
