### ISSUE TITLE
上传到fir不支持指定app 名称 

### ISSUE THREAD

**Issue by Cingjin** [FIRHQ/fastlane-plugin-fir_cli#23]
[--specify-app-display-name=SPECIFY_APP_DISPLAY_NAME]                  # 指定app 名称，可不可以支持一下自定义显示名称呢？

**Comment by jicheng1014** [comment]
理论上可以， 等下一个版本连同  fir-cli 一起更新吧

**Comment by jicheng1014** [comment]
因为审核原因， 关闭了修改名称
