### ISSUE TITLE
如何在Mac中使用FastLane导出apk到fir

### ISSUE THREAD

**Issue by amigo-wangwx** [FIRHQ/fastlane-plugin-fir_cli#25]
我遇到了两个问题

1.我按照wiki上描述填写了Fastfile提示我
  /usr/local/Cellar/fastlane/2.179.0/libexec/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as 
  keyword parameters is deprecated 
 [13:37:54]: Couldn't automatically detect the project file, please provide a path: 
2. 如何获取最新或者当前的Git changeLog提交给fir
应该怎么去做呢?

**Comment by jicheng1014** [comment]
这个  好像跟这个插件关系不大     是没有办法识别到项目文件

**Comment by amigo-wangwx** [comment]
> 这个 好像跟这个插件关系不大 是没有办法识别到项目文件

我是在Mac Android项目里运行,它提示我需要.xcode相关的文件,有什么办法么

**Comment by jicheng1014** [comment]
额  这个应该是个 fastlane 的问题, 您可以看看fastlane 的官网
