### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by neutronstarer** [FIRHQ/fastlane-plugin-fir_cli#32]
今天上传，开始报错，

D, [2022-11-30T19:24:34.287747 #65929] DEBUG -- : {"CONTENT-DISPOSITION"=>"attachment; filename* = UTF-8''ad-hoc.%E8%BF%9B%E9%97%A8%E8%B4%A2%E7%BB%8F.ipa", "Content-Type"=>"application/octet-stream", "date"=>"Wed, 30 Nov 2022 11:24:34 GMT", "x-oss-date"=>"Wed, 30 Nov 2022 11:24:34 GMT", "authorization"=>"OSS *******"}
E, [2022-11-30T19:25:31.796898 #65929] ERROR -- : upload binary ... error ! 503 Service Unavailable
E, [2022-11-30T19:25:31.796987 #65929] ERROR -- : binary upload to ali fail, 503 Service Unavailable

**Comment by jicheng1014** [comment]
老哥, 这个看起来像是阿里云挂掉了
