### ISSUE TITLE
specify_file_path 可以支持正则匹配吗？

### ISSUE THREAD

**Issue by chj-damon** [FIRHQ/fastlane-plugin-fir_cli#35]
现在我生成的apk文件名会根据versionCode和versionName自动变化，每发一个版本versionCode就会加1，这时候fastfile里面如果写死的话就不行了，有办法支持正则匹配的方式吗？

**Comment by jicheng1014** [comment]
目前不行哟。 只不过你可以用环境变量拼接一下呢

**Comment by chj-damon** [comment]
是的目前还不行，所以我的意思是这个插件可以支持一下这个功能吗？

**Comment by jicheng1014** [comment]
因为这个不属于插件的范围, 所以不会考虑这个功能,  这个是 fastfile 的工作范围

我记得如果不加 specify_file_path  fastlane 会自动找到当前编译的的 ipa 文件 , 确实不太清楚 apk 的情况

fastfile 本质ruby 的 dsl, 是支持运行 ruby 代码的, 您这个用ruby 代码非常好实现

你只需要这么做

```ruby
lane "custom upload"
  max_file = Dir.glob("*.apk").max_by {|f| f[/\d+/].to_i}
  fir_cli api_token: "xxxxx", specify_file_path: max_file
```

**Comment by chj-damon** [comment]
我看了一下文档，用官方提供的lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH] 解决了
