### ISSUE TITLE
能支持 --need_release_id 返回精确下载地址吗？

### ISSUE THREAD

**Issue by hongxinhope** [FIRHQ/fastlane-plugin-fir_cli#5]

**Comment by jicheng1014** [comment]
可以倒是可以的, 等我下个版本吧

但是注意一下   
releases 的保存是有数量限制的
如果您这边需要要求一直保持生效, 则需要使用 --force_pin_history  将其固定为历史版本    

目前我们releases 是30 个, 之后  最多 history_releases 是30 个   也就是说理论上你最多可以保存61 个版本. 如果有特殊需求需要更多版本, 可以和我联系

**Comment by hongxinhope** [comment]
能得到本次发布版本的精确下载地址就行了，否则还要去手动看一下。谢谢支持！

**Comment by jicheng1014** [comment]
Successfully registered gem: fastlane-plugin-fir_cli (2.0.1.2)

更新即可

**Comment by jicheng1014** [comment]
其实这个也蛮简单  就是兼容 fir-cli 的参数就好了  欢迎fork修改后 发pr

**Comment by hongxinhope** [comment]
@jicheng1014 环境变量是 fir_need_release_id，能否改成大写呢？风格统一些
