### ISSUE TITLE
怎么才能拿到带 release id 的精确下载地址 download_url 呢？

### ISSUE THREAD

**Issue by hongxinhope** [FIRHQ/fastlane-plugin-fir_cli#7]

**Comment by jicheng1014** [comment]
我是在日志里输出了    fir.im/xxx?release_id=xxxxx 的方式    其实    这个您也可以通过fastlane action 的返回值算出具体的下载的地址    

action 操作完毕后, 会返回  short  和relases_id 值

**Comment by jicheng1014** [comment]
举个例子    您要是带了  need_release_id: true 的话 

理论上他会输出类似的例子 

```
 [2019-12-17T14:18:02.294993 #44967]  INFO -- : ✈ -------------------------------------------- ✈
I, [2019-12-17T14:18:02.295023 #44967]  INFO -- : Published succeed: http://fir.im/xxxxxxx?release_id=xxxxxxx

```

您可以使用 grep 工具精确获得

当然如果您想在 Fastlane 中编程处理的话  可以在 Fastfile 中这么操作一下 

``` ruby
    # something in lane block
    answer = fir_cli api_token: "xxxx", need_release_id: true
    download_url = "https://fir.im/#{answer[:short]}?release_id=#{answer[:release_id]}"
```
之后您就可以拿到下载地址, 之后进行你想要实现的其他编程操作了

**Comment by hongxinhope** [comment]
@jicheng1014 已经搞定啦，谢谢！！能把 2.0.1.3 release 一下吗？

**Comment by hongxinhope** [comment]
看了一下 fir-cli 的代码，摸索出来了 https://github.com/FIRHQ/fir-cli/blob/27b0612630f88f0fcfa937d4bae54d383144b08e/lib/fir/util/publish.rb

**Comment by jicheng1014** [comment]
Successfully registered gem: fastlane-plugin-fir_cli (2.0.1.3)
Pushed fastlane-plugin-fir_cli 2.0.1.3 to rubygems.org
