### ISSUE TITLE
钉钉通知不能 at

### ISSUE THREAD

**Issue by relaxfinger** [FIRHQ/fastlane-plugin-fir_cli#8]
能否增加两个参数：
1，atMobiles 数组
2. 是否atAll

谢谢！

**Comment by jicheng1014** [comment]
行, 抽空我改下吧

**Comment by jicheng1014** [comment]
已经发到  fir-cli 的 beta 了  等到正式了  我就同步到这个插件里

**Comment by jicheng1014** [comment]
已上线

**Comment by relaxfinger** [comment]
fastlane-plugin-fir_cli 还是 2.0.1.3 似乎还没有更新啊，新的参数会报错

**Comment by relaxfinger** [comment]
请问 fastlane-plugin-fir_cli v2.0.3版本还没发布吧，更新不到啊，新的at相关的参数都还不能用。
