### ISSUE TITLE
请问 fastlane-plugin-fir_cli v2.0.3版本还没发布吧，更新不到啊，新的at相关的参数都还不能用。

### ISSUE THREAD

**Issue by relaxfinger** [FIRHQ/fastlane-plugin-fir_cli#9]

**Comment by relaxfinger** [comment]
[14:41:49]: You passed invalid parameters to 'fir_cli'.
[14:41:49]: Check out the error below and available options by running `fastlane action fir_cli`
+--------------------+---------------------------------------------------------------------------------------------------------------+
|                                                            Lane Context                                                            |
+--------------------+---------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                                           |
| PLATFORM_NAME      | ios                                                                                                           |
| LANE_NAME          | ios fir                                                                                                       |
| IPA_OUTPUT_PATH    | /Users/relaxfinger/Develop/YPCStorePro/YPCStorePro-test.ipa                                                   |
| XCODEBUILD_ARCHIVE | /Users/relaxfinger/Library/Developer/Xcode/Archives/2020-01-10/YPCStorePro-test 2020-01-10 14.39.35.xcarchive |
+--------------------+---------------------------------------------------------------------------------------------------------------+
[14:41:49]: Could not find option 'dingtalk_at_all' in the list of available options: api_token, specify_file_path, short, force_pin_history, skip_update_icon, specify_icon_file, changelog, open, password, switch_to_qiniu, need_release_id, dingtalk_access_token, dingtalk_custom_message

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | build_app        | 140         |
+------+------------------+-------------+

[14:41:49]: fastlane finished with errors

[!] Could not find option 'dingtalk_at_all' in the list of available options: api_token, specify_file_path, short, force_pin_history, skip_update_icon, specify_icon_file, changelog, open, password, switch_to_qiniu, need_release_id, dingtalk_access_token, dingtalk_custom_message

**Comment by jicheng1014** [comment]
sorry about that.

**Comment by jicheng1014** [comment]
https://rubygems.org/gems/fastlane-plugin-fir_cli   已经发布

**Comment by relaxfinger** [comment]
fastlane-plugin-fir_cli/lib/fastlane/plugin/fir_cli/actions/fir_cli_aciton.rb 文件中函数 self.run 中at相关的两个参数没有传进去，所以现在虽然at参数可用，但是还是不能at到人。

**Comment by jicheng1014** [comment]
确实是的呢  下次还是pr 吧 :D

**Comment by jicheng1014** [comment]
我重新上传了个版本  抱歉
